#version: '3'

services:
  ############################ User Service ############################
  mysql-user:
    image: mysql:latest
    container_name: mysql_user
    networks:
      - msa_network
    volumes:
      - ./User-service/db/conf.d:/etc/mysql/conf.d
      - ./User-service/db/data:/var/lib/mysql
      - ./User-service/db/initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "33061:3306"
    environment:
      - TZ=Asia/Seoul
      - MYSQL_ROOT_PASSWORD=user_root
      - MYSQL_DATABASE=user_db
      - MYSQL_USER=user_id
      - MYSQL_PASSWORD=user_pw
  User-service:
    image: msa-user-service:0.0.1-SNAPSHOT
    ports:
      - "8081:8080"
    depends_on:
      - mysql-user
    networks:
      - msa_network
    environment:
      - SPRINGDOC_API-DOCS_PATH=/user/api-docs
      - SPRINGDOC_SWAGGER-UI_PATH=/user/swagger-ui
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-user:33061/user_db?useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=user_id
      - SPRING_DATASOURCE_PASSWORD=user_pw
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.MySQL8Dialect
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update



networks:
  msa_network:
    driver: bridge